// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB5Nxptmo8Rq77q0rSQwM5LHyQkccjzGpk',
    appId: '1:381663361852:android:ccc63efab60ba62f633c39',
    messagingSenderId: '381663361852',
    projectId: 'craftybay-b5384',
    storageBucket: 'craftybay-b5384.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADsSBuccrJ_X__LEyK5jVFGk8Xlc7ovbg',
    appId: '1:381663361852:ios:f3f48b957b6c0087633c39',
    messagingSenderId: '381663361852',
    projectId: 'craftybay-b5384',
    storageBucket: 'craftybay-b5384.firebasestorage.app',
    iosBundleId: 'com.craftybay.craftybay',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNZ_kMxB7EeixSw3iJvFdRxkd5dt7Hqbo',
    appId: '1:381663361852:web:344de6b2e9ee84fa633c39',
    messagingSenderId: '381663361852',
    projectId: 'craftybay-b5384',
    authDomain: 'craftybay-b5384.firebaseapp.com',
    storageBucket: 'craftybay-b5384.firebasestorage.app',
    measurementId: 'G-HV4903NDYG',
  );

}